### ISSUE TITLE
/overview study cards fixed height

### ISSUE THREAD

**Issue by lguerdan** [lguerdan/tigerAware#3]
style.css overview card (264) has fixed height property and gets cut off on long survey titles. `display: table` fixes it but results in uneven layout

**Comment by nishantchettri** [comment]
Started working on this and changed card UI a bit. Should be looking better now

**Comment by lguerdan** [comment]
Great! Feel free to push it up on your own branch, that'll probably look the best

**Comment by lguerdan** [comment]
Fixed
